name: Документация Doxygen

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Генерация документации Doxygen
        uses: DenverCoder1/doxygen-github-pages-action@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: Doxyfile
